[program:r2d2-server]
directory=/home/naman/Desktop/R2D2-PI-Server
command=/home/naman/Desktop/R2D2-PI-Server/.venv/bin/uvicorn r2d2_server.main:app --host 127.0.0.1 --port 8000 --proxy-headers --forwarded-allow-ips=127.0.0.1 --env-file /home/naman/Desktop/R2D2-PI-Server/conf/uvicorn.env
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=naman
stdout_logfile=/home/naman/Desktop/R2D2-PI-Server/logs/supervisor.stdout.log
stderr_logfile=/home/naman/Desktop/R2D2-PI-Server/logs/supervisor.stderr.log
redirect_stderr=false
